18-Django_Level_Five/My_Learning_Users/My_Learning_Users/urls.py
from basic_app import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('basic_app', include('basic_app.urls'))
]

18-Django_Level_Five/My_Learning_Users/basic_app/urls.py
from django.urls import path, include
from basic_app import views

# TEMPLATE URLS!
app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name="register")
]

18-Django_Level_Five/My_Learning_Users/basic_app/models.py
from django.db import models
from django.contrib.auth .models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

18-Django_Level_Five/My_Learning_Users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

18-Django_Level_Five/My_Learning_Users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def register(request):
    
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            
            profile.save()

            registered = True
        
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

18-Django_Level_Five/My_Learning_Users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse">
                <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">Register</a> </li>
                </ul>
            </div>
        </nav>
    </div>
    
    <div class="container">
        {% block body_block %}
        {% endblock body_block %}
    </div>
</body>
</html>

18-Django_Level_Five/My_Learning_Users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>Django Level <strong>Five</strong></h1>
        </div>
    {% endblock body_block %}

18-Django_Level_Five/My_Learning_Users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% load static %}
    {% block body_block %}
        <div class="jumbotron">
            {% if registered %}
                <h1>Thank you for registering!</h1>
            {% else %}
                <h1>Register here!</h1>
                <h3>Fill out the form: </h3>

                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" name="" value="Register">
                </form>
            {% endif %}
        </div>
    {% endblock body_block %}