17-Django_Level_Four/My_learning_templates/My_basic_app/urls.py
from django.urls import path
from My_basic_app import views

# TEMPLATE TAGGING
app_name = 'My_basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

17-Django_Level_Four/My_learning_templates/My_learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from My_basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('my_basic_app/', include('My_basic_app.urls')),
]

17-Django_Level_Four/My_learning_templates/My_basic_app/models.py
from django.db import models

# Create your models here.

17-Django_Level_Four/My_learning_templates/My_basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 100} 
    return render(request, 'My_basic_app/index.html', context_dict)

def other(request):
    return render(request, 'My_basic_app/other.html')

def relative(request):
    return render(request, 'My_basic_app/relative_url_templates.html')

17-Django_Level_Four/My_learning_templates/templates/My_basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
	 crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
	 crossorigin="anonymous">

	</script>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{% url 'index' %}">Home</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'My_basic_app:other' %}">Other</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'My_basic_app:relative' %}">Relative</a>
      </li>
    </ul>
</nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
   </div>

</body>

</html>

17-Django_Level_Four/My_learning_templates/templates/My_basic_app/index.html
<!DOCTYPE html>
{% extends "My_basic_app/base.html" %} {% block body_block %}
<h1>WELCOME TO INDEX!</h1>
<!-- <h1>This is index.html page showing!</h1> -->
<h3>{{ text|cut:"world"|title }}</h3>
<h3>{{ number|add:"99" }}</h3>
{% endblock %}

17-Django_Level_Four/My_learning_templates/templates/My_basic_app/other.html
<!DOCTYPE html>
{% extends "My_basic_app/base.html" %}

{% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
{% endblock %}

17-Django_Level_Four/My_learning_templates/templates/My_basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "My_basic_app/base.html" %}

{% block body_block %}

	<h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>
    <a href="{% url 'My_basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
  
{% endblock %}